services:
  - type: web
    name: student-performance-prediction-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
